/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICustomer.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICustomer::OAICustomer(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICustomer::OAICustomer() {
    this->initializeModel();
}

OAICustomer::~OAICustomer() {}

void OAICustomer::initializeModel() {

    m_customer_id_isSet = false;
    m_customer_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_phone_isSet = false;
    m_phone_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;

    m_address_isSet = false;
    m_address_isValid = false;

    m_inn_isSet = false;
    m_inn_isValid = false;

    m_discount_rate_isSet = false;
    m_discount_rate_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;

    m_created_at_isSet = false;
    m_created_at_isValid = false;

    m_last_sale_date_isSet = false;
    m_last_sale_date_isValid = false;

    m_total_purchases_isSet = false;
    m_total_purchases_isValid = false;
}

void OAICustomer::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICustomer::fromJsonObject(QJsonObject json) {

    m_customer_id_isValid = ::OpenAPI::fromJsonValue(m_customer_id, json[QString("customer_id")]);
    m_customer_id_isSet = !json[QString("customer_id")].isNull() && m_customer_id_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_phone_isValid = ::OpenAPI::fromJsonValue(m_phone, json[QString("phone")]);
    m_phone_isSet = !json[QString("phone")].isNull() && m_phone_isValid;

    m_email_isValid = ::OpenAPI::fromJsonValue(m_email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;

    m_address_isValid = ::OpenAPI::fromJsonValue(m_address, json[QString("address")]);
    m_address_isSet = !json[QString("address")].isNull() && m_address_isValid;

    m_inn_isValid = ::OpenAPI::fromJsonValue(m_inn, json[QString("inn")]);
    m_inn_isSet = !json[QString("inn")].isNull() && m_inn_isValid;

    m_discount_rate_isValid = ::OpenAPI::fromJsonValue(m_discount_rate, json[QString("discount_rate")]);
    m_discount_rate_isSet = !json[QString("discount_rate")].isNull() && m_discount_rate_isValid;

    m_status_isValid = ::OpenAPI::fromJsonValue(m_status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;

    m_created_at_isValid = ::OpenAPI::fromJsonValue(m_created_at, json[QString("created_at")]);
    m_created_at_isSet = !json[QString("created_at")].isNull() && m_created_at_isValid;

    m_last_sale_date_isValid = ::OpenAPI::fromJsonValue(m_last_sale_date, json[QString("last_sale_date")]);
    m_last_sale_date_isSet = !json[QString("last_sale_date")].isNull() && m_last_sale_date_isValid;

    m_total_purchases_isValid = ::OpenAPI::fromJsonValue(m_total_purchases, json[QString("total_purchases")]);
    m_total_purchases_isSet = !json[QString("total_purchases")].isNull() && m_total_purchases_isValid;
}

QString OAICustomer::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICustomer::asJsonObject() const {
    QJsonObject obj;
    if (m_customer_id_isSet) {
        obj.insert(QString("customer_id"), ::OpenAPI::toJsonValue(m_customer_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_phone_isSet) {
        obj.insert(QString("phone"), ::OpenAPI::toJsonValue(m_phone));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::OpenAPI::toJsonValue(m_email));
    }
    if (m_address_isSet) {
        obj.insert(QString("address"), ::OpenAPI::toJsonValue(m_address));
    }
    if (m_inn_isSet) {
        obj.insert(QString("inn"), ::OpenAPI::toJsonValue(m_inn));
    }
    if (m_discount_rate_isSet) {
        obj.insert(QString("discount_rate"), ::OpenAPI::toJsonValue(m_discount_rate));
    }
    if (m_status_isSet) {
        obj.insert(QString("status"), ::OpenAPI::toJsonValue(m_status));
    }
    if (m_created_at_isSet) {
        obj.insert(QString("created_at"), ::OpenAPI::toJsonValue(m_created_at));
    }
    if (m_last_sale_date_isSet) {
        obj.insert(QString("last_sale_date"), ::OpenAPI::toJsonValue(m_last_sale_date));
    }
    if (m_total_purchases_isSet) {
        obj.insert(QString("total_purchases"), ::OpenAPI::toJsonValue(m_total_purchases));
    }
    return obj;
}

qint64 OAICustomer::getCustomerId() const {
    return m_customer_id;
}
void OAICustomer::setCustomerId(const qint64 &customer_id) {
    m_customer_id = customer_id;
    m_customer_id_isSet = true;
}

bool OAICustomer::is_customer_id_Set() const{
    return m_customer_id_isSet;
}

bool OAICustomer::is_customer_id_Valid() const{
    return m_customer_id_isValid;
}

QString OAICustomer::getName() const {
    return m_name;
}
void OAICustomer::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAICustomer::is_name_Set() const{
    return m_name_isSet;
}

bool OAICustomer::is_name_Valid() const{
    return m_name_isValid;
}

QString OAICustomer::getPhone() const {
    return m_phone;
}
void OAICustomer::setPhone(const QString &phone) {
    m_phone = phone;
    m_phone_isSet = true;
}

bool OAICustomer::is_phone_Set() const{
    return m_phone_isSet;
}

bool OAICustomer::is_phone_Valid() const{
    return m_phone_isValid;
}

QString OAICustomer::getEmail() const {
    return m_email;
}
void OAICustomer::setEmail(const QString &email) {
    m_email = email;
    m_email_isSet = true;
}

bool OAICustomer::is_email_Set() const{
    return m_email_isSet;
}

bool OAICustomer::is_email_Valid() const{
    return m_email_isValid;
}

QString OAICustomer::getAddress() const {
    return m_address;
}
void OAICustomer::setAddress(const QString &address) {
    m_address = address;
    m_address_isSet = true;
}

bool OAICustomer::is_address_Set() const{
    return m_address_isSet;
}

bool OAICustomer::is_address_Valid() const{
    return m_address_isValid;
}

QString OAICustomer::getInn() const {
    return m_inn;
}
void OAICustomer::setInn(const QString &inn) {
    m_inn = inn;
    m_inn_isSet = true;
}

bool OAICustomer::is_inn_Set() const{
    return m_inn_isSet;
}

bool OAICustomer::is_inn_Valid() const{
    return m_inn_isValid;
}

double OAICustomer::getDiscountRate() const {
    return m_discount_rate;
}
void OAICustomer::setDiscountRate(const double &discount_rate) {
    m_discount_rate = discount_rate;
    m_discount_rate_isSet = true;
}

bool OAICustomer::is_discount_rate_Set() const{
    return m_discount_rate_isSet;
}

bool OAICustomer::is_discount_rate_Valid() const{
    return m_discount_rate_isValid;
}

bool OAICustomer::isStatus() const {
    return m_status;
}
void OAICustomer::setStatus(const bool &status) {
    m_status = status;
    m_status_isSet = true;
}

bool OAICustomer::is_status_Set() const{
    return m_status_isSet;
}

bool OAICustomer::is_status_Valid() const{
    return m_status_isValid;
}

QDateTime OAICustomer::getCreatedAt() const {
    return m_created_at;
}
void OAICustomer::setCreatedAt(const QDateTime &created_at) {
    m_created_at = created_at;
    m_created_at_isSet = true;
}

bool OAICustomer::is_created_at_Set() const{
    return m_created_at_isSet;
}

bool OAICustomer::is_created_at_Valid() const{
    return m_created_at_isValid;
}

QDateTime OAICustomer::getLastSaleDate() const {
    return m_last_sale_date;
}
void OAICustomer::setLastSaleDate(const QDateTime &last_sale_date) {
    m_last_sale_date = last_sale_date;
    m_last_sale_date_isSet = true;
}

bool OAICustomer::is_last_sale_date_Set() const{
    return m_last_sale_date_isSet;
}

bool OAICustomer::is_last_sale_date_Valid() const{
    return m_last_sale_date_isValid;
}

double OAICustomer::getTotalPurchases() const {
    return m_total_purchases;
}
void OAICustomer::setTotalPurchases(const double &total_purchases) {
    m_total_purchases = total_purchases;
    m_total_purchases_isSet = true;
}

bool OAICustomer::is_total_purchases_Set() const{
    return m_total_purchases_isSet;
}

bool OAICustomer::is_total_purchases_Valid() const{
    return m_total_purchases_isValid;
}

bool OAICustomer::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_customer_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_phone_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_address_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_inn_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_discount_rate_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_created_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_last_sale_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_total_purchases_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICustomer::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_customer_id_isValid && m_name_isValid && m_phone_isValid && m_email_isValid && m_address_isValid && m_inn_isValid && m_status_isValid && m_created_at_isValid && m_last_sale_date_isValid && true;
}

} // namespace OpenAPI
