/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIDocumentStatusCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDocumentStatusCreate::OAIDocumentStatusCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDocumentStatusCreate::OAIDocumentStatusCreate() {
    this->initializeModel();
}

OAIDocumentStatusCreate::~OAIDocumentStatusCreate() {}

void OAIDocumentStatusCreate::initializeModel() {

    m_status_name_isSet = false;
    m_status_name_isValid = false;
}

void OAIDocumentStatusCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIDocumentStatusCreate::fromJsonObject(QJsonObject json) {

    m_status_name_isValid = ::OpenAPI::fromJsonValue(m_status_name, json[QString("status_name")]);
    m_status_name_isSet = !json[QString("status_name")].isNull() && m_status_name_isValid;
}

QString OAIDocumentStatusCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIDocumentStatusCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_status_name_isSet) {
        obj.insert(QString("status_name"), ::OpenAPI::toJsonValue(m_status_name));
    }
    return obj;
}

QString OAIDocumentStatusCreate::getStatusName() const {
    return m_status_name;
}
void OAIDocumentStatusCreate::setStatusName(const QString &status_name) {
    m_status_name = status_name;
    m_status_name_isSet = true;
}

bool OAIDocumentStatusCreate::is_status_name_Set() const{
    return m_status_name_isSet;
}

bool OAIDocumentStatusCreate::is_status_name_Valid() const{
    return m_status_name_isValid;
}

bool OAIDocumentStatusCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_status_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIDocumentStatusCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_status_name_isValid && true;
}

} // namespace OpenAPI
