/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDocumentStatusUpdate.h
 *
 * 
 */

#ifndef OAIDocumentStatusUpdate_H
#define OAIDocumentStatusUpdate_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDocumentStatusUpdate : public OAIObject {
public:
    OAIDocumentStatusUpdate();
    OAIDocumentStatusUpdate(QString json);
    ~OAIDocumentStatusUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getStatusName() const;
    void setStatusName(const QString &status_name);
    bool is_status_name_Set() const;
    bool is_status_name_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_status_name;
    bool m_status_name_isSet;
    bool m_status_name_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDocumentStatusUpdate)

#endif // OAIDocumentStatusUpdate_H
