/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDemandForecast.h
 *
 * 
 */

#ifndef OAIDemandForecast_H
#define OAIDemandForecast_H

#include <QJsonObject>

#include <QDate>
#include <QDateTime>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDemandForecast : public OAIObject {
public:
    OAIDemandForecast();
    OAIDemandForecast(QString json);
    ~OAIDemandForecast() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getForecastId() const;
    void setForecastId(const qint64 &forecast_id);
    bool is_forecast_id_Set() const;
    bool is_forecast_id_Valid() const;

    QDateTime getForecastDate() const;
    void setForecastDate(const QDateTime &forecast_date);
    bool is_forecast_date_Set() const;
    bool is_forecast_date_Valid() const;

    QDate getPeriodStart() const;
    void setPeriodStart(const QDate &period_start);
    bool is_period_start_Set() const;
    bool is_period_start_Valid() const;

    QDate getPeriodEnd() const;
    void setPeriodEnd(const QDate &period_end);
    bool is_period_end_Set() const;
    bool is_period_end_Valid() const;

    double getPredictedQuantity() const;
    void setPredictedQuantity(const double &predicted_quantity);
    bool is_predicted_quantity_Set() const;
    bool is_predicted_quantity_Valid() const;

    qint64 getRecordId() const;
    void setRecordId(const qint64 &record_id);
    bool is_record_id_Set() const;
    bool is_record_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_forecast_id;
    bool m_forecast_id_isSet;
    bool m_forecast_id_isValid;

    QDateTime m_forecast_date;
    bool m_forecast_date_isSet;
    bool m_forecast_date_isValid;

    QDate m_period_start;
    bool m_period_start_isSet;
    bool m_period_start_isValid;

    QDate m_period_end;
    bool m_period_end_isSet;
    bool m_period_end_isValid;

    double m_predicted_quantity;
    bool m_predicted_quantity_isSet;
    bool m_predicted_quantity_isValid;

    qint64 m_record_id;
    bool m_record_id_isSet;
    bool m_record_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDemandForecast)

#endif // OAIDemandForecast_H
