/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIDocumentStatus.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDocumentStatus::OAIDocumentStatus(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDocumentStatus::OAIDocumentStatus() {
    this->initializeModel();
}

OAIDocumentStatus::~OAIDocumentStatus() {}

void OAIDocumentStatus::initializeModel() {

    m_document_status_id_isSet = false;
    m_document_status_id_isValid = false;

    m_status_name_isSet = false;
    m_status_name_isValid = false;
}

void OAIDocumentStatus::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIDocumentStatus::fromJsonObject(QJsonObject json) {

    m_document_status_id_isValid = ::OpenAPI::fromJsonValue(m_document_status_id, json[QString("document_status_id")]);
    m_document_status_id_isSet = !json[QString("document_status_id")].isNull() && m_document_status_id_isValid;

    m_status_name_isValid = ::OpenAPI::fromJsonValue(m_status_name, json[QString("status_name")]);
    m_status_name_isSet = !json[QString("status_name")].isNull() && m_status_name_isValid;
}

QString OAIDocumentStatus::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIDocumentStatus::asJsonObject() const {
    QJsonObject obj;
    if (m_document_status_id_isSet) {
        obj.insert(QString("document_status_id"), ::OpenAPI::toJsonValue(m_document_status_id));
    }
    if (m_status_name_isSet) {
        obj.insert(QString("status_name"), ::OpenAPI::toJsonValue(m_status_name));
    }
    return obj;
}

qint64 OAIDocumentStatus::getDocumentStatusId() const {
    return m_document_status_id;
}
void OAIDocumentStatus::setDocumentStatusId(const qint64 &document_status_id) {
    m_document_status_id = document_status_id;
    m_document_status_id_isSet = true;
}

bool OAIDocumentStatus::is_document_status_id_Set() const{
    return m_document_status_id_isSet;
}

bool OAIDocumentStatus::is_document_status_id_Valid() const{
    return m_document_status_id_isValid;
}

QString OAIDocumentStatus::getStatusName() const {
    return m_status_name;
}
void OAIDocumentStatus::setStatusName(const QString &status_name) {
    m_status_name = status_name;
    m_status_name_isSet = true;
}

bool OAIDocumentStatus::is_status_name_Set() const{
    return m_status_name_isSet;
}

bool OAIDocumentStatus::is_status_name_Valid() const{
    return m_status_name_isValid;
}

bool OAIDocumentStatus::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_document_status_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIDocumentStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_document_status_id_isValid && m_status_name_isValid && true;
}

} // namespace OpenAPI
