/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIForecastsType.h
 *
 * 
 */

#ifndef OAIForecastsType_H
#define OAIForecastsType_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIForecastsType : public OAIObject {
public:
    OAIForecastsType();
    OAIForecastsType(QString json);
    ~OAIForecastsType() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getForecastsTypeId() const;
    void setForecastsTypeId(const qint64 &forecasts_type_id);
    bool is_forecasts_type_id_Set() const;
    bool is_forecasts_type_id_Valid() const;

    QString getNameForecastsType() const;
    void setNameForecastsType(const QString &name_forecasts_type);
    bool is_name_forecasts_type_Set() const;
    bool is_name_forecasts_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_forecasts_type_id;
    bool m_forecasts_type_id_isSet;
    bool m_forecasts_type_id_isValid;

    QString m_name_forecasts_type;
    bool m_name_forecasts_type_isSet;
    bool m_name_forecasts_type_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIForecastsType)

#endif // OAIForecastsType_H
