/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIForecastsType.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIForecastsType::OAIForecastsType(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIForecastsType::OAIForecastsType() {
    this->initializeModel();
}

OAIForecastsType::~OAIForecastsType() {}

void OAIForecastsType::initializeModel() {

    m_forecasts_type_id_isSet = false;
    m_forecasts_type_id_isValid = false;

    m_name_forecasts_type_isSet = false;
    m_name_forecasts_type_isValid = false;
}

void OAIForecastsType::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIForecastsType::fromJsonObject(QJsonObject json) {

    m_forecasts_type_id_isValid = ::OpenAPI::fromJsonValue(m_forecasts_type_id, json[QString("forecasts_type_id")]);
    m_forecasts_type_id_isSet = !json[QString("forecasts_type_id")].isNull() && m_forecasts_type_id_isValid;

    m_name_forecasts_type_isValid = ::OpenAPI::fromJsonValue(m_name_forecasts_type, json[QString("name_forecasts_type")]);
    m_name_forecasts_type_isSet = !json[QString("name_forecasts_type")].isNull() && m_name_forecasts_type_isValid;
}

QString OAIForecastsType::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIForecastsType::asJsonObject() const {
    QJsonObject obj;
    if (m_forecasts_type_id_isSet) {
        obj.insert(QString("forecasts_type_id"), ::OpenAPI::toJsonValue(m_forecasts_type_id));
    }
    if (m_name_forecasts_type_isSet) {
        obj.insert(QString("name_forecasts_type"), ::OpenAPI::toJsonValue(m_name_forecasts_type));
    }
    return obj;
}

qint64 OAIForecastsType::getForecastsTypeId() const {
    return m_forecasts_type_id;
}
void OAIForecastsType::setForecastsTypeId(const qint64 &forecasts_type_id) {
    m_forecasts_type_id = forecasts_type_id;
    m_forecasts_type_id_isSet = true;
}

bool OAIForecastsType::is_forecasts_type_id_Set() const{
    return m_forecasts_type_id_isSet;
}

bool OAIForecastsType::is_forecasts_type_id_Valid() const{
    return m_forecasts_type_id_isValid;
}

QString OAIForecastsType::getNameForecastsType() const {
    return m_name_forecasts_type;
}
void OAIForecastsType::setNameForecastsType(const QString &name_forecasts_type) {
    m_name_forecasts_type = name_forecasts_type;
    m_name_forecasts_type_isSet = true;
}

bool OAIForecastsType::is_name_forecasts_type_Set() const{
    return m_name_forecasts_type_isSet;
}

bool OAIForecastsType::is_name_forecasts_type_Valid() const{
    return m_name_forecasts_type_isValid;
}

bool OAIForecastsType::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_forecasts_type_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_forecasts_type_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIForecastsType::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_forecasts_type_id_isValid && m_name_forecasts_type_isValid && true;
}

} // namespace OpenAPI
