/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInline_object_1.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIInline_object_1::OAIInline_object_1(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIInline_object_1::OAIInline_object_1() {
    this->initializeModel();
}

OAIInline_object_1::~OAIInline_object_1() {}

void OAIInline_object_1::initializeModel() {

    m_message_isSet = false;
    m_message_isValid = false;

    m_errors_isSet = false;
    m_errors_isValid = false;
}

void OAIInline_object_1::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInline_object_1::fromJsonObject(QJsonObject json) {

    m_message_isValid = ::OpenAPI::fromJsonValue(m_message, json[QString("message")]);
    m_message_isSet = !json[QString("message")].isNull() && m_message_isValid;

    m_errors_isValid = ::OpenAPI::fromJsonValue(m_errors, json[QString("errors")]);
    m_errors_isSet = !json[QString("errors")].isNull() && m_errors_isValid;
}

QString OAIInline_object_1::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInline_object_1::asJsonObject() const {
    QJsonObject obj;
    if (m_message_isSet) {
        obj.insert(QString("message"), ::OpenAPI::toJsonValue(m_message));
    }
    if (m_errors.size() > 0) {
        obj.insert(QString("errors"), ::OpenAPI::toJsonValue(m_errors));
    }
    return obj;
}

QString OAIInline_object_1::getMessage() const {
    return m_message;
}
void OAIInline_object_1::setMessage(const QString &message) {
    m_message = message;
    m_message_isSet = true;
}

bool OAIInline_object_1::is_message_Set() const{
    return m_message_isSet;
}

bool OAIInline_object_1::is_message_Valid() const{
    return m_message_isValid;
}

QList<QString> OAIInline_object_1::getErrors() const {
    return m_errors;
}
void OAIInline_object_1::setErrors(const QList<QString> &errors) {
    m_errors = errors;
    m_errors_isSet = true;
}

bool OAIInline_object_1::is_errors_Set() const{
    return m_errors_isSet;
}

bool OAIInline_object_1::is_errors_Valid() const{
    return m_errors_isValid;
}

bool OAIInline_object_1::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_errors.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInline_object_1::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
