/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInventory.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIInventory::OAIInventory(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIInventory::OAIInventory() {
    this->initializeModel();
}

OAIInventory::~OAIInventory() {}

void OAIInventory::initializeModel() {

    m_inventory_id_isSet = false;
    m_inventory_id_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;

    m_reserved_quantity_isSet = false;
    m_reserved_quantity_isValid = false;

    m_last_count_date_isSet = false;
    m_last_count_date_isValid = false;

    m_storage_location_isSet = false;
    m_storage_location_isValid = false;

    m_batch_number_isSet = false;
    m_batch_number_isValid = false;
}

void OAIInventory::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInventory::fromJsonObject(QJsonObject json) {

    m_inventory_id_isValid = ::OpenAPI::fromJsonValue(m_inventory_id, json[QString("inventory_id")]);
    m_inventory_id_isSet = !json[QString("inventory_id")].isNull() && m_inventory_id_isValid;

    m_quantity_isValid = ::OpenAPI::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;

    m_reserved_quantity_isValid = ::OpenAPI::fromJsonValue(m_reserved_quantity, json[QString("reserved_quantity")]);
    m_reserved_quantity_isSet = !json[QString("reserved_quantity")].isNull() && m_reserved_quantity_isValid;

    m_last_count_date_isValid = ::OpenAPI::fromJsonValue(m_last_count_date, json[QString("last_count_date")]);
    m_last_count_date_isSet = !json[QString("last_count_date")].isNull() && m_last_count_date_isValid;

    m_storage_location_isValid = ::OpenAPI::fromJsonValue(m_storage_location, json[QString("storage_location")]);
    m_storage_location_isSet = !json[QString("storage_location")].isNull() && m_storage_location_isValid;

    m_batch_number_isValid = ::OpenAPI::fromJsonValue(m_batch_number, json[QString("batch_number")]);
    m_batch_number_isSet = !json[QString("batch_number")].isNull() && m_batch_number_isValid;
}

QString OAIInventory::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInventory::asJsonObject() const {
    QJsonObject obj;
    if (m_inventory_id_isSet) {
        obj.insert(QString("inventory_id"), ::OpenAPI::toJsonValue(m_inventory_id));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::OpenAPI::toJsonValue(m_quantity));
    }
    if (m_reserved_quantity_isSet) {
        obj.insert(QString("reserved_quantity"), ::OpenAPI::toJsonValue(m_reserved_quantity));
    }
    if (m_last_count_date_isSet) {
        obj.insert(QString("last_count_date"), ::OpenAPI::toJsonValue(m_last_count_date));
    }
    if (m_storage_location_isSet) {
        obj.insert(QString("storage_location"), ::OpenAPI::toJsonValue(m_storage_location));
    }
    if (m_batch_number_isSet) {
        obj.insert(QString("batch_number"), ::OpenAPI::toJsonValue(m_batch_number));
    }
    return obj;
}

qint64 OAIInventory::getInventoryId() const {
    return m_inventory_id;
}
void OAIInventory::setInventoryId(const qint64 &inventory_id) {
    m_inventory_id = inventory_id;
    m_inventory_id_isSet = true;
}

bool OAIInventory::is_inventory_id_Set() const{
    return m_inventory_id_isSet;
}

bool OAIInventory::is_inventory_id_Valid() const{
    return m_inventory_id_isValid;
}

double OAIInventory::getQuantity() const {
    return m_quantity;
}
void OAIInventory::setQuantity(const double &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool OAIInventory::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool OAIInventory::is_quantity_Valid() const{
    return m_quantity_isValid;
}

double OAIInventory::getReservedQuantity() const {
    return m_reserved_quantity;
}
void OAIInventory::setReservedQuantity(const double &reserved_quantity) {
    m_reserved_quantity = reserved_quantity;
    m_reserved_quantity_isSet = true;
}

bool OAIInventory::is_reserved_quantity_Set() const{
    return m_reserved_quantity_isSet;
}

bool OAIInventory::is_reserved_quantity_Valid() const{
    return m_reserved_quantity_isValid;
}

QDateTime OAIInventory::getLastCountDate() const {
    return m_last_count_date;
}
void OAIInventory::setLastCountDate(const QDateTime &last_count_date) {
    m_last_count_date = last_count_date;
    m_last_count_date_isSet = true;
}

bool OAIInventory::is_last_count_date_Set() const{
    return m_last_count_date_isSet;
}

bool OAIInventory::is_last_count_date_Valid() const{
    return m_last_count_date_isValid;
}

QString OAIInventory::getStorageLocation() const {
    return m_storage_location;
}
void OAIInventory::setStorageLocation(const QString &storage_location) {
    m_storage_location = storage_location;
    m_storage_location_isSet = true;
}

bool OAIInventory::is_storage_location_Set() const{
    return m_storage_location_isSet;
}

bool OAIInventory::is_storage_location_Valid() const{
    return m_storage_location_isValid;
}

QString OAIInventory::getBatchNumber() const {
    return m_batch_number;
}
void OAIInventory::setBatchNumber(const QString &batch_number) {
    m_batch_number = batch_number;
    m_batch_number_isSet = true;
}

bool OAIInventory::is_batch_number_Set() const{
    return m_batch_number_isSet;
}

bool OAIInventory::is_batch_number_Valid() const{
    return m_batch_number_isValid;
}

bool OAIInventory::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_inventory_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_reserved_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_last_count_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_storage_location_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_batch_number_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInventory::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_inventory_id_isValid && m_last_count_date_isValid && m_storage_location_isValid && m_batch_number_isValid && true;
}

} // namespace OpenAPI
