/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMovementTypeUpdate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIMovementTypeUpdate::OAIMovementTypeUpdate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIMovementTypeUpdate::OAIMovementTypeUpdate() {
    this->initializeModel();
}

OAIMovementTypeUpdate::~OAIMovementTypeUpdate() {}

void OAIMovementTypeUpdate::initializeModel() {

    m_movement_type_isSet = false;
    m_movement_type_isValid = false;
}

void OAIMovementTypeUpdate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMovementTypeUpdate::fromJsonObject(QJsonObject json) {

    m_movement_type_isValid = ::OpenAPI::fromJsonValue(m_movement_type, json[QString("movement_type")]);
    m_movement_type_isSet = !json[QString("movement_type")].isNull() && m_movement_type_isValid;
}

QString OAIMovementTypeUpdate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMovementTypeUpdate::asJsonObject() const {
    QJsonObject obj;
    if (m_movement_type_isSet) {
        obj.insert(QString("movement_type"), ::OpenAPI::toJsonValue(m_movement_type));
    }
    return obj;
}

QString OAIMovementTypeUpdate::getMovementType() const {
    return m_movement_type;
}
void OAIMovementTypeUpdate::setMovementType(const QString &movement_type) {
    m_movement_type = movement_type;
    m_movement_type_isSet = true;
}

bool OAIMovementTypeUpdate::is_movement_type_Set() const{
    return m_movement_type_isSet;
}

bool OAIMovementTypeUpdate::is_movement_type_Valid() const{
    return m_movement_type_isValid;
}

bool OAIMovementTypeUpdate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_movement_type_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMovementTypeUpdate::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
