/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMovementType.h
 *
 * 
 */

#ifndef OAIMovementType_H
#define OAIMovementType_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIMovementType : public OAIObject {
public:
    OAIMovementType();
    OAIMovementType(QString json);
    ~OAIMovementType() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getMovementTypeId() const;
    void setMovementTypeId(const qint64 &movement_type_id);
    bool is_movement_type_id_Set() const;
    bool is_movement_type_id_Valid() const;

    QString getMovementType() const;
    void setMovementType(const QString &movement_type);
    bool is_movement_type_Set() const;
    bool is_movement_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_movement_type_id;
    bool m_movement_type_id_isSet;
    bool m_movement_type_id_isValid;

    QString m_movement_type;
    bool m_movement_type_isSet;
    bool m_movement_type_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMovementType)

#endif // OAIMovementType_H
