/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINotification.h
 *
 * 
 */

#ifndef OAINotification_H
#define OAINotification_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAINotification : public OAIObject {
public:
    OAINotification();
    OAINotification(QString json);
    ~OAINotification() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getNotificationId() const;
    void setNotificationId(const qint64 &notification_id);
    bool is_notification_id_Set() const;
    bool is_notification_id_Valid() const;

    QString getTitle() const;
    void setTitle(const QString &title);
    bool is_title_Set() const;
    bool is_title_Valid() const;

    QString getMessage() const;
    void setMessage(const QString &message);
    bool is_message_Set() const;
    bool is_message_Valid() const;

    bool isIsRead() const;
    void setIsRead(const bool &is_read);
    bool is_is_read_Set() const;
    bool is_is_read_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_notification_id;
    bool m_notification_id_isSet;
    bool m_notification_id_isValid;

    QString m_title;
    bool m_title_isSet;
    bool m_title_isValid;

    QString m_message;
    bool m_message_isSet;
    bool m_message_isValid;

    bool m_is_read;
    bool m_is_read_isSet;
    bool m_is_read_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAINotification)

#endif // OAINotification_H
