/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISalesHistoryUpdate.h
 *
 * 
 */

#ifndef OAISalesHistoryUpdate_H
#define OAISalesHistoryUpdate_H

#include <QJsonObject>

#include <QDate>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISalesHistoryUpdate : public OAIObject {
public:
    OAISalesHistoryUpdate();
    OAISalesHistoryUpdate(QString json);
    ~OAISalesHistoryUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QDate getDate() const;
    void setDate(const QDate &date);
    bool is_date_Set() const;
    bool is_date_Valid() const;

    double getQuantity() const;
    void setQuantity(const double &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    double getPrice() const;
    void setPrice(const double &price);
    bool is_price_Set() const;
    bool is_price_Valid() const;

    double getProfit() const;
    void setProfit(const double &profit);
    bool is_profit_Set() const;
    bool is_profit_Valid() const;

    qint64 getProductId() const;
    void setProductId(const qint64 &product_id);
    bool is_product_id_Set() const;
    bool is_product_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QDate m_date;
    bool m_date_isSet;
    bool m_date_isValid;

    double m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;

    double m_price;
    bool m_price_isSet;
    bool m_price_isValid;

    double m_profit;
    bool m_profit_isSet;
    bool m_profit_isValid;

    qint64 m_product_id;
    bool m_product_id_isSet;
    bool m_product_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISalesHistoryUpdate)

#endif // OAISalesHistoryUpdate_H
