/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISupplierCreate.h
 *
 * 
 */

#ifndef OAISupplierCreate_H
#define OAISupplierCreate_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISupplierCreate : public OAIObject {
public:
    OAISupplierCreate();
    OAISupplierCreate(QString json);
    ~OAISupplierCreate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getNameCompany() const;
    void setNameCompany(const QString &name_company);
    bool is_name_company_Set() const;
    bool is_name_company_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    QString getEmail() const;
    void setEmail(const QString &email);
    bool is_email_Set() const;
    bool is_email_Valid() const;

    QString getAddress() const;
    void setAddress(const QString &address);
    bool is_address_Set() const;
    bool is_address_Valid() const;

    QString getInn() const;
    void setInn(const QString &inn);
    bool is_inn_Set() const;
    bool is_inn_Valid() const;

    QString getKpp() const;
    void setKpp(const QString &kpp);
    bool is_kpp_Set() const;
    bool is_kpp_Valid() const;

    QString getBankDetails() const;
    void setBankDetails(const QString &bank_details);
    bool is_bank_details_Set() const;
    bool is_bank_details_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_name_company;
    bool m_name_company_isSet;
    bool m_name_company_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString m_phone;
    bool m_phone_isSet;
    bool m_phone_isValid;

    QString m_email;
    bool m_email_isSet;
    bool m_email_isValid;

    QString m_address;
    bool m_address_isSet;
    bool m_address_isValid;

    QString m_inn;
    bool m_inn_isSet;
    bool m_inn_isValid;

    QString m_kpp;
    bool m_kpp_isSet;
    bool m_kpp_isValid;

    QString m_bank_details;
    bool m_bank_details_isSet;
    bool m_bank_details_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISupplierCreate)

#endif // OAISupplierCreate_H
