/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUserProfileCreate.h
 *
 * 
 */

#ifndef OAIUserProfileCreate_H
#define OAIUserProfileCreate_H

#include <QJsonObject>

#include <QDate>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUserProfileCreate : public OAIObject {
public:
    OAIUserProfileCreate();
    OAIUserProfileCreate(QString json);
    ~OAIUserProfileCreate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getUserId() const;
    void setUserId(const qint64 &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    qint64 getRoleId() const;
    void setRoleId(const qint64 &role_id);
    bool is_role_id_Set() const;
    bool is_role_id_Valid() const;

    QString getFullName() const;
    void setFullName(const QString &full_name);
    bool is_full_name_Set() const;
    bool is_full_name_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    QString getPosition() const;
    void setPosition(const QString &position);
    bool is_position_Set() const;
    bool is_position_Valid() const;

    QString getDepartment() const;
    void setDepartment(const QString &department);
    bool is_department_Set() const;
    bool is_department_Valid() const;

    QDate getBirthDate() const;
    void setBirthDate(const QDate &birth_date);
    bool is_birth_date_Set() const;
    bool is_birth_date_Valid() const;

    QString getAvatarPath() const;
    void setAvatarPath(const QString &avatar_path);
    bool is_avatar_path_Set() const;
    bool is_avatar_path_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    qint64 m_role_id;
    bool m_role_id_isSet;
    bool m_role_id_isValid;

    QString m_full_name;
    bool m_full_name_isSet;
    bool m_full_name_isValid;

    QString m_phone;
    bool m_phone_isSet;
    bool m_phone_isValid;

    QString m_position;
    bool m_position_isSet;
    bool m_position_isValid;

    QString m_department;
    bool m_department_isSet;
    bool m_department_isValid;

    QDate m_birth_date;
    bool m_birth_date_isSet;
    bool m_birth_date_isValid;

    QString m_avatar_path;
    bool m_avatar_path_isSet;
    bool m_avatar_path_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUserProfileCreate)

#endif // OAIUserProfileCreate_H
