/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUserCreate::OAIUserCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserCreate::OAIUserCreate() {
    this->initializeModel();
}

OAIUserCreate::~OAIUserCreate() {}

void OAIUserCreate::initializeModel() {

    m_username_isSet = false;
    m_username_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;

    m_is_active_isSet = false;
    m_is_active_isValid = false;

    m_inn_isSet = false;
    m_inn_isValid = false;

    m_organization_isSet = false;
    m_organization_isValid = false;

    m_role_id_isSet = false;
    m_role_id_isValid = false;
}

void OAIUserCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserCreate::fromJsonObject(QJsonObject json) {

    m_username_isValid = ::OpenAPI::fromJsonValue(m_username, json[QString("username")]);
    m_username_isSet = !json[QString("username")].isNull() && m_username_isValid;

    m_password_isValid = ::OpenAPI::fromJsonValue(m_password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;

    m_email_isValid = ::OpenAPI::fromJsonValue(m_email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;

    m_is_active_isValid = ::OpenAPI::fromJsonValue(m_is_active, json[QString("is_active")]);
    m_is_active_isSet = !json[QString("is_active")].isNull() && m_is_active_isValid;

    m_inn_isValid = ::OpenAPI::fromJsonValue(m_inn, json[QString("inn")]);
    m_inn_isSet = !json[QString("inn")].isNull() && m_inn_isValid;

    m_organization_isValid = ::OpenAPI::fromJsonValue(m_organization, json[QString("organization")]);
    m_organization_isSet = !json[QString("organization")].isNull() && m_organization_isValid;

    m_role_id_isValid = ::OpenAPI::fromJsonValue(m_role_id, json[QString("role_id")]);
    m_role_id_isSet = !json[QString("role_id")].isNull() && m_role_id_isValid;
}

QString OAIUserCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_username_isSet) {
        obj.insert(QString("username"), ::OpenAPI::toJsonValue(m_username));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::OpenAPI::toJsonValue(m_password));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::OpenAPI::toJsonValue(m_email));
    }
    if (m_is_active_isSet) {
        obj.insert(QString("is_active"), ::OpenAPI::toJsonValue(m_is_active));
    }
    if (m_inn_isSet) {
        obj.insert(QString("inn"), ::OpenAPI::toJsonValue(m_inn));
    }
    if (m_organization_isSet) {
        obj.insert(QString("organization"), ::OpenAPI::toJsonValue(m_organization));
    }
    if (m_role_id_isSet) {
        obj.insert(QString("role_id"), ::OpenAPI::toJsonValue(m_role_id));
    }
    return obj;
}

QString OAIUserCreate::getUsername() const {
    return m_username;
}
void OAIUserCreate::setUsername(const QString &username) {
    m_username = username;
    m_username_isSet = true;
}

bool OAIUserCreate::is_username_Set() const{
    return m_username_isSet;
}

bool OAIUserCreate::is_username_Valid() const{
    return m_username_isValid;
}

QString OAIUserCreate::getPassword() const {
    return m_password;
}
void OAIUserCreate::setPassword(const QString &password) {
    m_password = password;
    m_password_isSet = true;
}

bool OAIUserCreate::is_password_Set() const{
    return m_password_isSet;
}

bool OAIUserCreate::is_password_Valid() const{
    return m_password_isValid;
}

QString OAIUserCreate::getEmail() const {
    return m_email;
}
void OAIUserCreate::setEmail(const QString &email) {
    m_email = email;
    m_email_isSet = true;
}

bool OAIUserCreate::is_email_Set() const{
    return m_email_isSet;
}

bool OAIUserCreate::is_email_Valid() const{
    return m_email_isValid;
}

bool OAIUserCreate::isIsActive() const {
    return m_is_active;
}
void OAIUserCreate::setIsActive(const bool &is_active) {
    m_is_active = is_active;
    m_is_active_isSet = true;
}

bool OAIUserCreate::is_is_active_Set() const{
    return m_is_active_isSet;
}

bool OAIUserCreate::is_is_active_Valid() const{
    return m_is_active_isValid;
}

QString OAIUserCreate::getInn() const {
    return m_inn;
}
void OAIUserCreate::setInn(const QString &inn) {
    m_inn = inn;
    m_inn_isSet = true;
}

bool OAIUserCreate::is_inn_Set() const{
    return m_inn_isSet;
}

bool OAIUserCreate::is_inn_Valid() const{
    return m_inn_isValid;
}

QString OAIUserCreate::getOrganization() const {
    return m_organization;
}
void OAIUserCreate::setOrganization(const QString &organization) {
    m_organization = organization;
    m_organization_isSet = true;
}

bool OAIUserCreate::is_organization_Set() const{
    return m_organization_isSet;
}

bool OAIUserCreate::is_organization_Valid() const{
    return m_organization_isValid;
}

qint64 OAIUserCreate::getRoleId() const {
    return m_role_id;
}
void OAIUserCreate::setRoleId(const qint64 &role_id) {
    m_role_id = role_id;
    m_role_id_isSet = true;
}

bool OAIUserCreate::is_role_id_Set() const{
    return m_role_id_isSet;
}

bool OAIUserCreate::is_role_id_Valid() const{
    return m_role_id_isValid;
}

bool OAIUserCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_username_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_is_active_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_inn_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_organization_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_role_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_username_isValid && m_password_isValid && m_email_isValid && m_role_id_isValid && true;
}

} // namespace OpenAPI
