/**
 * Warehouse Management API
 * API for managing all operations available in the application
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIWarehouseCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIWarehouseCreate::OAIWarehouseCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIWarehouseCreate::OAIWarehouseCreate() {
    this->initializeModel();
}

OAIWarehouseCreate::~OAIWarehouseCreate() {}

void OAIWarehouseCreate::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_address_isSet = false;
    m_address_isValid = false;

    m_total_capacity_isSet = false;
    m_total_capacity_isValid = false;

    m_current_utilization_isSet = false;
    m_current_utilization_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;
}

void OAIWarehouseCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIWarehouseCreate::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_address_isValid = ::OpenAPI::fromJsonValue(m_address, json[QString("address")]);
    m_address_isSet = !json[QString("address")].isNull() && m_address_isValid;

    m_total_capacity_isValid = ::OpenAPI::fromJsonValue(m_total_capacity, json[QString("total_capacity")]);
    m_total_capacity_isSet = !json[QString("total_capacity")].isNull() && m_total_capacity_isValid;

    m_current_utilization_isValid = ::OpenAPI::fromJsonValue(m_current_utilization, json[QString("current_utilization")]);
    m_current_utilization_isSet = !json[QString("current_utilization")].isNull() && m_current_utilization_isValid;

    m_status_isValid = ::OpenAPI::fromJsonValue(m_status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;
}

QString OAIWarehouseCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIWarehouseCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_address_isSet) {
        obj.insert(QString("address"), ::OpenAPI::toJsonValue(m_address));
    }
    if (m_total_capacity_isSet) {
        obj.insert(QString("total_capacity"), ::OpenAPI::toJsonValue(m_total_capacity));
    }
    if (m_current_utilization_isSet) {
        obj.insert(QString("current_utilization"), ::OpenAPI::toJsonValue(m_current_utilization));
    }
    if (m_status_isSet) {
        obj.insert(QString("status"), ::OpenAPI::toJsonValue(m_status));
    }
    return obj;
}

QString OAIWarehouseCreate::getName() const {
    return m_name;
}
void OAIWarehouseCreate::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAIWarehouseCreate::is_name_Set() const{
    return m_name_isSet;
}

bool OAIWarehouseCreate::is_name_Valid() const{
    return m_name_isValid;
}

QString OAIWarehouseCreate::getAddress() const {
    return m_address;
}
void OAIWarehouseCreate::setAddress(const QString &address) {
    m_address = address;
    m_address_isSet = true;
}

bool OAIWarehouseCreate::is_address_Set() const{
    return m_address_isSet;
}

bool OAIWarehouseCreate::is_address_Valid() const{
    return m_address_isValid;
}

double OAIWarehouseCreate::getTotalCapacity() const {
    return m_total_capacity;
}
void OAIWarehouseCreate::setTotalCapacity(const double &total_capacity) {
    m_total_capacity = total_capacity;
    m_total_capacity_isSet = true;
}

bool OAIWarehouseCreate::is_total_capacity_Set() const{
    return m_total_capacity_isSet;
}

bool OAIWarehouseCreate::is_total_capacity_Valid() const{
    return m_total_capacity_isValid;
}

double OAIWarehouseCreate::getCurrentUtilization() const {
    return m_current_utilization;
}
void OAIWarehouseCreate::setCurrentUtilization(const double &current_utilization) {
    m_current_utilization = current_utilization;
    m_current_utilization_isSet = true;
}

bool OAIWarehouseCreate::is_current_utilization_Set() const{
    return m_current_utilization_isSet;
}

bool OAIWarehouseCreate::is_current_utilization_Valid() const{
    return m_current_utilization_isValid;
}

bool OAIWarehouseCreate::isStatus() const {
    return m_status;
}
void OAIWarehouseCreate::setStatus(const bool &status) {
    m_status = status;
    m_status_isSet = true;
}

bool OAIWarehouseCreate::is_status_Set() const{
    return m_status_isSet;
}

bool OAIWarehouseCreate::is_status_Valid() const{
    return m_status_isValid;
}

bool OAIWarehouseCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_address_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_total_capacity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_current_utilization_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIWarehouseCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_name_isValid && m_address_isValid && m_total_capacity_isValid && m_status_isValid && true;
}

} // namespace OpenAPI
